---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.73.146
      ansible_user: admin
lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 158.160.21.32
      ansible_user: admin
